/**
 * Eventos del sistema
 */
export const ACTIVITY_ACTIONS = {
  // Usuario
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
  USER_2FA_ENABLED: 'USER_2FA_ENABLED',
  USER_2FA_DISABLED: 'USER_2FA_DISABLED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  USER_AVATAR_UPDATED: 'USER_AVATAR_UPDATED',
  USER_SETTINGS_UPDATED: 'USER_SETTINGS_UPDATED',
  
  // Tenant
  TENANT_CREATED: 'TENANT_CREATED',
  TENANT_UPDATED: 'TENANT_UPDATED',
  TENANT_DELETED: 'TENANT_DELETED',
  TENANT_SETTINGS_UPDATED: 'TENANT_SETTINGS_UPDATED',
  TENANT_OWNER_CHANGED: 'TENANT_OWNER_CHANGED',
  
  // Team
  USER_INVITED: 'USER_INVITED',
  USER_JOINED: 'USER_JOINED',
  USER_REMOVED: 'USER_REMOVED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_PERMISSIONS_UPDATED: 'USER_PERMISSIONS_UPDATED',
  
  // Suscripciones
  SUBSCRIPTION_CREATED: 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_UPDATED: 'SUBSCRIPTION_UPDATED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  PAYMENT_METHOD_ADDED: 'PAYMENT_METHOD_ADDED',
  PAYMENT_METHOD_REMOVED: 'PAYMENT_METHOD_REMOVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  
  // Archivos
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_UPDATED: 'FILE_UPDATED',
  FILE_DELETED: 'FILE_DELETED',
  FILE_SHARED: 'FILE_SHARED',
  FILE_UNSHARED: 'FILE_UNSHARED',
  FILE_DOWNLOADED: 'FILE_DOWNLOADED',
  FILE_MOVED: 'FILE_MOVED',
  FILE_DUPLICATED: 'FILE_DUPLICATED',
  FILE_VERSION_CREATED: 'FILE_VERSION_CREATED',
  FILE_VERSION_RESTORED: 'FILE_VERSION_RESTORED',
  
  // Mensajes
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_EDITED: 'MESSAGE_EDITED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',
  CHANNEL_CREATED: 'CHANNEL_CREATED',
  CHANNEL_UPDATED: 'CHANNEL_UPDATED',
  CHANNEL_DELETED: 'CHANNEL_DELETED',
  CHANNEL_MEMBER_ADDED: 'CHANNEL_MEMBER_ADDED',
  CHANNEL_MEMBER_REMOVED: 'CHANNEL_MEMBER_REMOVED',
  
  // Notificaciones
  NOTIFICATION_SENT: 'NOTIFICATION_SENT',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_PREFERENCES_UPDATED: 'NOTIFICATION_PREFERENCES_UPDATED',
  
  // Seguridad
  SECURITY_BREACH_DETECTED: 'SECURITY_BREACH_DETECTED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  FAILED_LOGIN_ATTEMPT: 'FAILED_LOGIN_ATTEMPT',
  API_KEY_CREATED: 'API_KEY_CREATED',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  
  // Sistema
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  BULK_OPERATION: 'BULK_OPERATION',
  DATA_EXPORT: 'DATA_EXPORT',
  DATA_IMPORT: 'DATA_IMPORT',
  BACKUP_CREATED: 'BACKUP_CREATED',
  MAINTENANCE_MODE_ENABLED: 'MAINTENANCE_MODE_ENABLED',
  MAINTENANCE_MODE_DISABLED: 'MAINTENANCE_MODE_DISABLED'
};

/**
 * Eventos de WebSocket
 */
export const SOCKET_EVENTS = {
  // Conexión
  CONNECT: 'connect',
  DISCONNECT: 'disconnect',
  ERROR: 'error',
  RECONNECT: 'reconnect',
  
  // Autenticación
  AUTHENTICATED: 'authenticated',
  UNAUTHORIZED: 'unauthorized',
  
  // Usuarios
  USER_ONLINE: 'user:online',
  USER_OFFLINE: 'user:offline',
  USER_STATUS_CHANGED: 'user:status:changed',
  USER_PRESENCE_CHANGED: 'user:presence:changed',
  
  // Mensajes
  NEW_MESSAGE: 'message:new',
  MESSAGE_EDITED: 'message:edited',
  MESSAGE_DELETED: 'message:deleted',
  MESSAGE_READ: 'message:read',
  MESSAGES_READ: 'messages:read',
  
  // Typing
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  USER_TYPING: 'user:typing',
  USER_STOPPED_TYPING: 'user:stopped:typing',
  
  // Canales
  JOIN_CHANNEL: 'channel:join',
  LEAVE_CHANNEL: 'channel:leave',
  JOINED_CHANNEL: 'channel:joined',
  LEFT_CHANNEL: 'channel:left',
  CHANNEL_UPDATED: 'channel:updated',
  CHANNEL_DELETED: 'channel:deleted',
  
  // Notificaciones
  NEW_NOTIFICATION: 'notification:new',
  NOTIFICATION_READ: 'notification:read',
  ALL_NOTIFICATIONS_READ: 'notifications:all:read',
  
  // Archivos
  FILE_UPLOADED: 'file:uploaded',
  FILE_DELETED: 'file:deleted',
  FILE_SHARED: 'file:shared',
  
  // Actividad
  ACTIVITY_UPDATE: 'activity:update',
  
  // Reacciones
  REACTION_ADDED: 'reaction:added',
  REACTION_REMOVED: 'reaction:removed',
  
  // Sistema
  SYSTEM_ANNOUNCEMENT: 'system:announcement',
  MAINTENANCE_MODE: 'system:maintenance',
  UPDATE_PRESENCE: 'presence:update',
  PING: 'ping',
  PONG: 'pong'
};

/**
 * Prioridades de eventos
 */
export enum EventPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  URGENT = 'urgent',
  CRITICAL = 'critical'
}

/**
 * Categorías de eventos para filtrado
 */
export enum EventCategory {
  USER = 'user',
  TENANT = 'tenant',
  TEAM = 'team',
  BILLING = 'billing',
  FILE = 'file',
  COMMUNICATION = 'communication',
  SECURITY = 'security',
  SYSTEM = 'system'
}

/**
 * Mapeo de acciones a categorías
 */
export const ACTION_CATEGORIES: Record<string, EventCategory> = {
  // Usuario
  [ACTIVITY_ACTIONS.USER_CREATED]: EventCategory.USER,
  [ACTIVITY_ACTIONS.USER_UPDATED]: EventCategory.USER,
  [ACTIVITY_ACTIONS.USER_DELETED]: EventCategory.USER,
  [ACTIVITY_ACTIONS.USER_LOGIN]: EventCategory.USER,
  [ACTIVITY_ACTIONS.USER_LOGOUT]: EventCategory.USER,
  
  // Tenant
  [ACTIVITY_ACTIONS.TENANT_CREATED]: EventCategory.TENANT,
  [ACTIVITY_ACTIONS.TENANT_UPDATED]: EventCategory.TENANT,
  [ACTIVITY_ACTIONS.TENANT_DELETED]: EventCategory.TENANT,
  
  // Team
  [ACTIVITY_ACTIONS.USER_INVITED]: EventCategory.TEAM,
  [ACTIVITY_ACTIONS.USER_JOINED]: EventCategory.TEAM,
  [ACTIVITY_ACTIONS.USER_REMOVED]: EventCategory.TEAM,
  
  // Billing
  [ACTIVITY_ACTIONS.SUBSCRIPTION_CREATED]: EventCategory.BILLING,
  [ACTIVITY_ACTIONS.SUBSCRIPTION_CANCELLED]: EventCategory.BILLING,
  [ACTIVITY_ACTIONS.PAYMENT_SUCCEEDED]: EventCategory.BILLING,
  
  // Archivos
  [ACTIVITY_ACTIONS.FILE_UPLOADED]: EventCategory.FILE,
  [ACTIVITY_ACTIONS.FILE_DELETED]: EventCategory.FILE,
  [ACTIVITY_ACTIONS.FILE_SHARED]: EventCategory.FILE,
  
  // Comunicación
  [ACTIVITY_ACTIONS.MESSAGE_SENT]: EventCategory.COMMUNICATION,
  [ACTIVITY_ACTIONS.CHANNEL_CREATED]: EventCategory.COMMUNICATION,
  
  // Seguridad
  [ACTIVITY_ACTIONS.SECURITY_BREACH_DETECTED]: EventCategory.SECURITY,
  [ACTIVITY_ACTIONS.FAILED_LOGIN_ATTEMPT]: EventCategory.SECURITY,
  
  // Sistema
  [ACTIVITY_ACTIONS.SYSTEM_ERROR]: EventCategory.SYSTEM,
  [ACTIVITY_ACTIONS.MAINTENANCE_MODE_ENABLED]: EventCategory.SYSTEM
};
